name: Test Win

on: 
  push:
    tags:
      - v*
      - w*

jobs:
  release-windows:
    env:
      REPOSITORY_NAME: owle
      BUILD_DIRECTORY: cmake-build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      id: build
      shell: bash
      run: |
        cmake -B ${BUILD_DIRECTORY}
        cmake --build ${BUILD_DIRECTORY} --target ${REPOSITORY_NAME}_Test -j 4 --config Release

    - name: test
      if: failure() && steps.build.outcome == 'failure'
      run: |
        pwd; find . | sort | sed '1d;s/^\.//;s/\/\([^/]*\)$/|--\1/;s/\/[^/|]*/|  /g'

    - name: Test
      run: |
        ./${BUILD_DIRECTORY}/test/${REPOSITORY_NAME}_Test.exe