name: Test OSX

on: 
  push:
    tags:
      - v*
      - o*

jobs:
  release-osx:
    env:
      REPOSITORY_NAME: owle
      BUILD_DIRECTORY: cmake-build
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        cmake -B ${BUILD_DIRECTORY}_debug -DCMAKE_BUILD_TYPE=Debug
        cmake --build ${BUILD_DIRECTORY}_debug --target ${REPOSITORY_NAME}_Test -j 4
        cmake -B ${BUILD_DIRECTORY}_release -DCMAKE_BUILD_TYPE=Release
        cmake --build ${BUILD_DIRECTORY}_release --target ${REPOSITORY_NAME}_Test -j 4

    - name: Test
      run: |
        ./${BUILD_DIRECTORY}_debug/test/${REPOSITORY_NAME}_Test
        ./${BUILD_DIRECTORY}_release/test/${REPOSITORY_NAME}_Test
