name: Test Win

on: 
  push:
    tags:
      - v*
      - w*

jobs:
  release-windows:
    env:
      REPOSITORY_NAME: owle
      BUILD_DIRECTORY: cmake-build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      shell: bash
      run: |
        cmake -B ${BUILD_DIRECTORY}
        cmake --build ${BUILD_DIRECTORY} --target ${REPOSITORY_NAME}_Test -j 4 --config Release

    - name: Test
      id: testing
      run: |
        ./${BUILD_DIRECTORY}/test/Release/${REPOSITORY_NAME}_Test.exe
